// <auto-generated />
using System;
using MdbTask.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MdbTask.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("CastMedia", b =>
                {
                    b.Property<int>("CastId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MediaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CastId", "MediaId");

                    b.HasIndex("MediaId");

                    b.ToTable("CastMedia");

                    b.HasData(
                        new
                        {
                            CastId = 6,
                            MediaId = 1
                        },
                        new
                        {
                            CastId = 5,
                            MediaId = 1
                        },
                        new
                        {
                            CastId = 3,
                            MediaId = 2
                        },
                        new
                        {
                            CastId = 2,
                            MediaId = 2
                        },
                        new
                        {
                            CastId = 4,
                            MediaId = 3
                        },
                        new
                        {
                            CastId = 3,
                            MediaId = 3
                        },
                        new
                        {
                            CastId = 1,
                            MediaId = 4
                        },
                        new
                        {
                            CastId = 2,
                            MediaId = 4
                        },
                        new
                        {
                            CastId = 6,
                            MediaId = 5
                        },
                        new
                        {
                            CastId = 5,
                            MediaId = 5
                        },
                        new
                        {
                            CastId = 6,
                            MediaId = 6
                        },
                        new
                        {
                            CastId = 5,
                            MediaId = 6
                        },
                        new
                        {
                            CastId = 5,
                            MediaId = 7
                        },
                        new
                        {
                            CastId = 4,
                            MediaId = 7
                        },
                        new
                        {
                            CastId = 9,
                            MediaId = 8
                        },
                        new
                        {
                            CastId = 8,
                            MediaId = 8
                        },
                        new
                        {
                            CastId = 7,
                            MediaId = 9
                        },
                        new
                        {
                            CastId = 6,
                            MediaId = 9
                        },
                        new
                        {
                            CastId = 6,
                            MediaId = 10
                        },
                        new
                        {
                            CastId = 5,
                            MediaId = 10
                        },
                        new
                        {
                            CastId = 3,
                            MediaId = 11
                        },
                        new
                        {
                            CastId = 2,
                            MediaId = 11
                        },
                        new
                        {
                            CastId = 6,
                            MediaId = 12
                        },
                        new
                        {
                            CastId = 5,
                            MediaId = 12
                        },
                        new
                        {
                            CastId = 2,
                            MediaId = 13
                        },
                        new
                        {
                            CastId = 1,
                            MediaId = 13
                        },
                        new
                        {
                            CastId = 10,
                            MediaId = 14
                        },
                        new
                        {
                            CastId = 9,
                            MediaId = 14
                        },
                        new
                        {
                            CastId = 10,
                            MediaId = 15
                        },
                        new
                        {
                            CastId = 9,
                            MediaId = 15
                        },
                        new
                        {
                            CastId = 1,
                            MediaId = 16
                        },
                        new
                        {
                            CastId = 2,
                            MediaId = 16
                        },
                        new
                        {
                            CastId = 10,
                            MediaId = 17
                        },
                        new
                        {
                            CastId = 9,
                            MediaId = 17
                        },
                        new
                        {
                            CastId = 8,
                            MediaId = 18
                        },
                        new
                        {
                            CastId = 7,
                            MediaId = 18
                        },
                        new
                        {
                            CastId = 9,
                            MediaId = 19
                        },
                        new
                        {
                            CastId = 8,
                            MediaId = 19
                        },
                        new
                        {
                            CastId = 2,
                            MediaId = 20
                        },
                        new
                        {
                            CastId = 1,
                            MediaId = 20
                        },
                        new
                        {
                            CastId = 1,
                            MediaId = 21
                        },
                        new
                        {
                            CastId = 2,
                            MediaId = 21
                        },
                        new
                        {
                            CastId = 5,
                            MediaId = 22
                        },
                        new
                        {
                            CastId = 4,
                            MediaId = 22
                        },
                        new
                        {
                            CastId = 1,
                            MediaId = 23
                        },
                        new
                        {
                            CastId = 2,
                            MediaId = 23
                        },
                        new
                        {
                            CastId = 2,
                            MediaId = 24
                        },
                        new
                        {
                            CastId = 1,
                            MediaId = 24
                        },
                        new
                        {
                            CastId = 4,
                            MediaId = 25
                        },
                        new
                        {
                            CastId = 3,
                            MediaId = 25
                        },
                        new
                        {
                            CastId = 9,
                            MediaId = 26
                        },
                        new
                        {
                            CastId = 8,
                            MediaId = 26
                        },
                        new
                        {
                            CastId = 6,
                            MediaId = 27
                        },
                        new
                        {
                            CastId = 5,
                            MediaId = 27
                        },
                        new
                        {
                            CastId = 10,
                            MediaId = 28
                        },
                        new
                        {
                            CastId = 9,
                            MediaId = 28
                        },
                        new
                        {
                            CastId = 4,
                            MediaId = 29
                        },
                        new
                        {
                            CastId = 3,
                            MediaId = 29
                        },
                        new
                        {
                            CastId = 9,
                            MediaId = 30
                        },
                        new
                        {
                            CastId = 8,
                            MediaId = 30
                        },
                        new
                        {
                            CastId = 8,
                            MediaId = 31
                        },
                        new
                        {
                            CastId = 7,
                            MediaId = 31
                        },
                        new
                        {
                            CastId = 1,
                            MediaId = 32
                        },
                        new
                        {
                            CastId = 2,
                            MediaId = 32
                        },
                        new
                        {
                            CastId = 6,
                            MediaId = 33
                        },
                        new
                        {
                            CastId = 5,
                            MediaId = 33
                        },
                        new
                        {
                            CastId = 4,
                            MediaId = 34
                        },
                        new
                        {
                            CastId = 3,
                            MediaId = 34
                        },
                        new
                        {
                            CastId = 6,
                            MediaId = 35
                        },
                        new
                        {
                            CastId = 5,
                            MediaId = 35
                        },
                        new
                        {
                            CastId = 5,
                            MediaId = 36
                        },
                        new
                        {
                            CastId = 4,
                            MediaId = 36
                        },
                        new
                        {
                            CastId = 4,
                            MediaId = 37
                        },
                        new
                        {
                            CastId = 3,
                            MediaId = 37
                        },
                        new
                        {
                            CastId = 9,
                            MediaId = 38
                        },
                        new
                        {
                            CastId = 8,
                            MediaId = 38
                        },
                        new
                        {
                            CastId = 6,
                            MediaId = 39
                        },
                        new
                        {
                            CastId = 5,
                            MediaId = 39
                        },
                        new
                        {
                            CastId = 1,
                            MediaId = 40
                        },
                        new
                        {
                            CastId = 2,
                            MediaId = 40
                        });
                });

            modelBuilder.Entity("MdbTask.Data.Models.Cast", b =>
                {
                    b.Property<int>("CastId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("CastId");

                    b.ToTable("Cast");

                    b.HasData(
                        new
                        {
                            CastId = 1,
                            Name = "Tim Robbins"
                        },
                        new
                        {
                            CastId = 2,
                            Name = "Morgan Freeman"
                        },
                        new
                        {
                            CastId = 3,
                            Name = "Bob Gunton"
                        },
                        new
                        {
                            CastId = 4,
                            Name = "William Sadler"
                        },
                        new
                        {
                            CastId = 5,
                            Name = "Clancy Brown"
                        },
                        new
                        {
                            CastId = 6,
                            Name = "Uma Thurman"
                        },
                        new
                        {
                            CastId = 7,
                            Name = "Rebecca Williams"
                        },
                        new
                        {
                            CastId = 8,
                            Name = "Sally Field"
                        },
                        new
                        {
                            CastId = 9,
                            Name = "Carrie-Anne Moss"
                        },
                        new
                        {
                            CastId = 10,
                            Name = "Gloria Foster"
                        });
                });

            modelBuilder.Entity("MdbTask.Data.Models.Media", b =>
                {
                    b.Property<int>("MediaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descritpion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("MediaId");

                    b.ToTable("Media");

                    b.HasData(
                        new
                        {
                            MediaId = 1,
                            Descritpion = "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
                            Image = "76dc4726-424b-4b81-b6f4-f9ffa4bf1734.PNG",
                            ReleaseDate = new DateTime(1994, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Shawshank Redemption",
                            Type = 1
                        },
                        new
                        {
                            MediaId = 2,
                            Descritpion = "An organized crime dynasty's aging patriarch transfers control of his clandestine empire to his reluctant son.",
                            Image = "32ab2181-3042-4737-96e6-6d22d2099346.PNG",
                            ReleaseDate = new DateTime(1972, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Godfather",
                            Type = 1
                        },
                        new
                        {
                            MediaId = 3,
                            Descritpion = "The early life and career of Vito Corleone in 1920s New York City is portrayed, while his son, Michael, expands and tightens his grip on the family crime syndicate.",
                            Image = "7e5bd243-8464-4e66-8209-067d09782b9e.PNG",
                            ReleaseDate = new DateTime(1974, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Godfather: Part II",
                            Type = 1
                        },
                        new
                        {
                            MediaId = 4,
                            Descritpion = "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
                            Image = "acdbb57f-ea31-4796-bcca-19ee0859a95a.PNG",
                            ReleaseDate = new DateTime(2008, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Dark Knight",
                            Type = 1
                        },
                        new
                        {
                            MediaId = 5,
                            Descritpion = "A jury holdout attempts to prevent a miscarriage of justice by forcing his colleagues to reconsider the evidence.",
                            Image = "d1b10603-f921-4958-add9-2cf24917e5c7.PNG",
                            ReleaseDate = new DateTime(1957, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "12 Angry Men",
                            Type = 1
                        },
                        new
                        {
                            MediaId = 6,
                            Descritpion = "In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.",
                            Image = "2675bc9d-b461-4c80-aa58-eeaf1ea4351f.PNG",
                            ReleaseDate = new DateTime(1993, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Schindler's List",
                            Type = 1
                        },
                        new
                        {
                            MediaId = 7,
                            Descritpion = "Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.",
                            Image = "18f1125b-6306-48e4-8f9f-263d76018a79.PNG",
                            ReleaseDate = new DateTime(2003, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Lord of the Rings: The Return of the King",
                            Type = 1
                        },
                        new
                        {
                            MediaId = 8,
                            Descritpion = "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
                            Image = "0d7b6135-16d4-4586-b417-6a48e5c7837c.PNG",
                            ReleaseDate = new DateTime(1994, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Pulp Fiction",
                            Type = 1
                        },
                        new
                        {
                            MediaId = 9,
                            Descritpion = "A bounty hunting scam joins two men in an uneasy alliance against a third in a race to find a fortune in gold buried in a remote cemetery.",
                            Image = "886a7fcd-d44a-410a-bd43-c6499fc4ea3c.PNG",
                            ReleaseDate = new DateTime(1966, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Good, the Bad and the Ugly",
                            Type = 1
                        },
                        new
                        {
                            MediaId = 10,
                            Descritpion = "A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.",
                            Image = "a5394d5f-cf3a-4f4a-a073-33f01537343e.PNG",
                            ReleaseDate = new DateTime(2001, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Lord of the Rings: The Fellowship of the Ring",
                            Type = 1
                        },
                        new
                        {
                            MediaId = 11,
                            Descritpion = "An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into much more.",
                            Image = "b03ba6df-c0b3-473b-9054-c11b8e72172c.PNG",
                            ReleaseDate = new DateTime(1999, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Fight Club",
                            Type = 1
                        },
                        new
                        {
                            MediaId = 12,
                            Descritpion = "The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal and other historical events unfold from the perspective of an Alabama man with an IQ of 75, whose only desire is to be reunited with his childhood sweetheart.",
                            Image = "1c615d7a-4eb2-4df2-961b-ee495d56fcde.PNG",
                            ReleaseDate = new DateTime(1994, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Forrest Gump",
                            Type = 1
                        },
                        new
                        {
                            MediaId = 13,
                            Descritpion = "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
                            Image = "908728fd-3cde-4d75-b0fa-78e9e6eeddb4.PNG",
                            ReleaseDate = new DateTime(2010, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Inception",
                            Type = 1
                        },
                        new
                        {
                            MediaId = 14,
                            Descritpion = "While Frodo and Sam edge closer to Mordor with the help of the shifty Gollum, the divided fellowship makes a stand against Sauron's new ally, Saruman, and his hordes of Isengard.",
                            Image = "11fb7a34-bc30-4add-b6e4-ee69fb60e841.PNG",
                            ReleaseDate = new DateTime(2002, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Lord of the Rings: The Two Towers",
                            Type = 1
                        },
                        new
                        {
                            MediaId = 15,
                            Descritpion = "When a beautiful stranger leads computer hacker Neo to a forbidding underworld, he discovers the shocking truth--the life he knows is the elaborate deception of an evil cyber-intelligence.",
                            Image = "ea1cf8c2-cb50-4a3c-8454-b15f1e6b8417.PNG",
                            ReleaseDate = new DateTime(1999, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Matrix",
                            Type = 1
                        },
                        new
                        {
                            MediaId = 16,
                            Descritpion = "The story of Henry Hill and his life in the mob, covering his relationship with his wife Karen Hill and his mob partners Jimmy Conway and Tommy DeVito in the Italian-American crime syndicate.",
                            Image = "524d78a2-cbcf-4d35-9700-0dc1e4dd14c1.PNG",
                            ReleaseDate = new DateTime(1990, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Goodfellas",
                            Type = 1
                        },
                        new
                        {
                            MediaId = 17,
                            Descritpion = "A poor village under attack by bandits recruits seven unemployed samurai to help them defend themselves.",
                            Image = "35f15079-9c99-4c88-8040-6d4fca4f1fa5.PNG",
                            ReleaseDate = new DateTime(1954, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Seven Samurai",
                            Type = 1
                        },
                        new
                        {
                            MediaId = 18,
                            Descritpion = "Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his motives.",
                            Image = "5ca1d05b-0c72-4686-860b-c6d2cb21ba95.PNG",
                            ReleaseDate = new DateTime(1995, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Se7en",
                            Type = 1
                        },
                        new
                        {
                            MediaId = 19,
                            Descritpion = "A young F.B.I. cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer, a madman who skins his victims.",
                            Image = "9100a14d-a3d1-4811-976e-575f619d01d4.PNG",
                            ReleaseDate = new DateTime(1991, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Silence of the Lambs",
                            Type = 1
                        },
                        new
                        {
                            MediaId = 20,
                            Descritpion = "In the slums of Rio, two kids' paths diverge as one struggles to become a photographer and the other a kingpin.",
                            Image = "27514c79-8c30-477a-8c0a-38e9078f7147.PNG",
                            ReleaseDate = new DateTime(2002, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "City of God",
                            Type = 1
                        },
                        new
                        {
                            MediaId = 21,
                            Descritpion = "Wildlife documentary series with David Attenborough, beginning with a look at the remote islands which offer sanctuary to some of the planet's rarest creatures, to the beauty of cities, which are home to humans, and animals.",
                            Image = "bfd415ff-e78c-4b14-ace6-7bad9ae53f37.PNG",
                            ReleaseDate = new DateTime(2016, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Planet Earth II",
                            Type = 0
                        },
                        new
                        {
                            MediaId = 22,
                            Descritpion = "Emmy Award-winning, 11 episodes, five years in the making, the most expensive nature documentary series ever commissioned by the BBC, and the first to be filmed in high definition.",
                            Image = "740d3ede-41c0-43c6-a3cb-7cdb0082a6fa.PNG",
                            ReleaseDate = new DateTime(2006, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Planet Earth",
                            Type = 0
                        },
                        new
                        {
                            MediaId = 23,
                            Descritpion = "A high school chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine in order to secure his family's future.",
                            Image = "2fb29410-c0dc-4d46-949c-4a1815d3b50f.PNG",
                            ReleaseDate = new DateTime(2008, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Breaking Bad",
                            Type = 0
                        },
                        new
                        {
                            MediaId = 24,
                            Descritpion = "The story of Easy Company of the U.S. Army 101st Airborne Division and their mission in World War II Europe, from Operation Overlord to V-J Day.",
                            Image = "6e7edc1a-bc77-4253-aa96-ed5e91dc42b3.PNG",
                            ReleaseDate = new DateTime(2001, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Band of Brothers",
                            Type = 0
                        },
                        new
                        {
                            MediaId = 25,
                            Descritpion = "In April 1986, an explosion at the Chernobyl nuclear power plant in the Union of Soviet Socialist Republics becomes one of the world's worst man-made catastrophes.",
                            Image = "17513a86-fdc0-4598-bec4-52acd627cc36.PNG",
                            ReleaseDate = new DateTime(2019, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Chernobyl",
                            Type = 0
                        },
                        new
                        {
                            MediaId = 26,
                            Descritpion = "The Baltimore drug scene, as seen through the eyes of drug dealers and law enforcement.",
                            Image = "6150136a-4ce7-4c9b-a49e-68ec6c9fe642.PNG",
                            ReleaseDate = new DateTime(2000, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Wire",
                            Type = 0
                        },
                        new
                        {
                            MediaId = 27,
                            Descritpion = "In a war-torn world of elemental magic, a young boy reawakens to undertake a dangerous mystic quest to fulfill his destiny as the Avatar, and bring peace to the world.",
                            Image = "85dc2dbe-d959-417e-b403-e12a8fe8afb5.PNG",
                            ReleaseDate = new DateTime(2005, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Avatar: The Last Airbender",
                            Type = 0
                        },
                        new
                        {
                            MediaId = 28,
                            Descritpion = "Nine noble families fight for control over the lands of Westeros, while an ancient enemy returns after being dormant for millennia.",
                            Image = "6fad8c23-c2c8-45b3-8baf-47495dece884.PNG",
                            ReleaseDate = new DateTime(2011, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Game of Thrones",
                            Type = 0
                        },
                        new
                        {
                            MediaId = 29,
                            Descritpion = "New Jersey mob boss Tony Soprano deals with personal and professional issues in his home and business life that affect his mental state, leading him to seek professional psychiatric counseling.",
                            Image = "6562d6af-f04d-4246-8304-2a62c0ac1945.PNG",
                            ReleaseDate = new DateTime(1999, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Sopranos",
                            Type = 0
                        },
                        new
                        {
                            MediaId = 30,
                            Descritpion = "An animated series that follows the exploits of a super scientist and his not-so-bright grandson.",
                            Image = "756a163a-adf9-45e3-bbbf-c00f9aed8b18.PNG",
                            ReleaseDate = new DateTime(2000, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Rick and Morty",
                            Type = 0
                        },
                        new
                        {
                            MediaId = 31,
                            Descritpion = "A groundbreaking 26-part documentary series narrated by the actor Laurence Olivier about the deadliest conflict in history, World War II.",
                            Image = "b7c5c80e-4e4a-4072-919f-5b2b82aa2d1a.PNG",
                            ReleaseDate = new DateTime(1973, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The World at War",
                            Type = 0
                        },
                        new
                        {
                            MediaId = 32,
                            Descritpion = "A modern update finds the famous sleuth and his doctor partner solving crime in 21st century London.",
                            Image = "8d758e36-b365-4ab7-8d47-e125b98c165e.PNG",
                            ReleaseDate = new DateTime(2010, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Sherlock",
                            Type = 0
                        },
                        new
                        {
                            MediaId = 33,
                            Descritpion = "Ordinary people find themselves in extraordinarily astounding situations, which they each try to solve in a remarkable manner.",
                            Image = "23c49b20-e975-4840-86a0-a18a5543faa8.PNG",
                            ReleaseDate = new DateTime(1959, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Twilight Zone",
                            Type = 0
                        },
                        new
                        {
                            MediaId = 34,
                            Descritpion = "Five hundred years in the future, a renegade crew aboard a small spacecraft tries to survive as they travel the unknown parts of the galaxy and evade warring factions as well as authority agents out to get them.",
                            Image = "162c4579-c6b9-4eae-b773-8ae1e6ef69e5.PNG",
                            ReleaseDate = new DateTime(2002, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Firefly",
                            Type = 0
                        },
                        new
                        {
                            MediaId = 35,
                            Descritpion = "An intelligent high school student goes on a secret crusade to eliminate criminals from the world after discovering a notebook capable of killing anyone whose name is written into it.",
                            Image = "a8f5c87c-6fad-477a-9a09-4c125ed37f69.PNG",
                            ReleaseDate = new DateTime(2006, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Death Note",
                            Type = 0
                        },
                        new
                        {
                            MediaId = 36,
                            Descritpion = "Seasonal anthology series in which police investigations unearth the personal and professional secrets of those involved, both within and outside the law.",
                            Image = "31121abe-e86f-4843-9baa-711b33928fb4.PNG",
                            ReleaseDate = new DateTime(2014, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "True Detective",
                            Type = 0
                        },
                        new
                        {
                            MediaId = 37,
                            Descritpion = "The futuristic misadventures and tragedies of an easygoing bounty hunter and his partners.",
                            Image = "c1ad8f44-fc28-4f7d-8c99-59485b74cd06.PNG",
                            ReleaseDate = new DateTime(1998, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Cowboy Bebop",
                            Type = 0
                        },
                        new
                        {
                            MediaId = 38,
                            Descritpion = "A mockumentary on a group of typical office workers, where the workday consists of ego clashes, inappropriate behavior, and tedium.",
                            Image = "f8279730-3905-4497-946d-5377e20ae4be.PNG",
                            ReleaseDate = new DateTime(2005, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Office",
                            Type = 0
                        },
                        new
                        {
                            MediaId = 39,
                            Descritpion = "Various chronicles of deception, intrigue and murder in and around frozen Minnesota. Yet all of these tales mysteriously lead back one way or another to Fargo, North Dakota.",
                            Image = "526abfac-a3f1-40a8-b58c-1a8649088182.PNG",
                            ReleaseDate = new DateTime(2014, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Fargo",
                            Type = 0
                        },
                        new
                        {
                            MediaId = 40,
                            Descritpion = "Comedy that follows two brothers from London's rough Peckham estate as they wheel and deal through a number of dodgy deals and search for the big score that'll make them millionaires.",
                            Image = "d5d7d230-f594-4783-9063-21176004a786.PNG",
                            ReleaseDate = new DateTime(1981, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Only Fools and Horses",
                            Type = 0
                        });
                });

            modelBuilder.Entity("MdbTask.Data.Models.Rating", b =>
                {
                    b.Property<int>("RatingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MediaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserRating")
                        .HasColumnType("INTEGER");

                    b.HasKey("RatingId");

                    b.HasIndex("MediaId");

                    b.ToTable("Ratings");

                    b.HasData(
                        new
                        {
                            RatingId = 1,
                            MediaId = 19,
                            UserRating = 3
                        },
                        new
                        {
                            RatingId = 2,
                            MediaId = 27,
                            UserRating = 5
                        },
                        new
                        {
                            RatingId = 3,
                            MediaId = 24,
                            UserRating = 3
                        },
                        new
                        {
                            RatingId = 4,
                            MediaId = 37,
                            UserRating = 2
                        },
                        new
                        {
                            RatingId = 5,
                            MediaId = 15,
                            UserRating = 4
                        },
                        new
                        {
                            RatingId = 6,
                            MediaId = 28,
                            UserRating = 2
                        },
                        new
                        {
                            RatingId = 7,
                            MediaId = 15,
                            UserRating = 3
                        },
                        new
                        {
                            RatingId = 8,
                            MediaId = 6,
                            UserRating = 1
                        },
                        new
                        {
                            RatingId = 9,
                            MediaId = 7,
                            UserRating = 2
                        },
                        new
                        {
                            RatingId = 10,
                            MediaId = 28,
                            UserRating = 4
                        },
                        new
                        {
                            RatingId = 11,
                            MediaId = 21,
                            UserRating = 1
                        },
                        new
                        {
                            RatingId = 12,
                            MediaId = 35,
                            UserRating = 3
                        },
                        new
                        {
                            RatingId = 13,
                            MediaId = 10,
                            UserRating = 4
                        },
                        new
                        {
                            RatingId = 14,
                            MediaId = 31,
                            UserRating = 1
                        },
                        new
                        {
                            RatingId = 15,
                            MediaId = 22,
                            UserRating = 2
                        },
                        new
                        {
                            RatingId = 16,
                            MediaId = 1,
                            UserRating = 4
                        },
                        new
                        {
                            RatingId = 17,
                            MediaId = 33,
                            UserRating = 2
                        },
                        new
                        {
                            RatingId = 18,
                            MediaId = 22,
                            UserRating = 4
                        },
                        new
                        {
                            RatingId = 19,
                            MediaId = 16,
                            UserRating = 4
                        },
                        new
                        {
                            RatingId = 20,
                            MediaId = 31,
                            UserRating = 4
                        },
                        new
                        {
                            RatingId = 21,
                            MediaId = 25,
                            UserRating = 3
                        },
                        new
                        {
                            RatingId = 22,
                            MediaId = 1,
                            UserRating = 2
                        },
                        new
                        {
                            RatingId = 23,
                            MediaId = 5,
                            UserRating = 3
                        },
                        new
                        {
                            RatingId = 24,
                            MediaId = 7,
                            UserRating = 3
                        },
                        new
                        {
                            RatingId = 25,
                            MediaId = 17,
                            UserRating = 2
                        });
                });

            modelBuilder.Entity("CastMedia", b =>
                {
                    b.HasOne("MdbTask.Data.Models.Cast", null)
                        .WithMany()
                        .HasForeignKey("CastId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MdbTask.Data.Models.Media", null)
                        .WithMany()
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MdbTask.Data.Models.Rating", b =>
                {
                    b.HasOne("MdbTask.Data.Models.Media", "Media")
                        .WithMany("Ratings")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Media");
                });

            modelBuilder.Entity("MdbTask.Data.Models.Media", b =>
                {
                    b.Navigation("Ratings");
                });
#pragma warning restore 612, 618
        }
    }
}
